### ISSUE TITLE
Make submodule for maps

### ISSUE THREAD

**Issue by scj643** [Repraance/SIFCardManager#2]
having https://github.com/Repraance/SIFCardManager/tree/master/assets point to where you get you're source files from would make maintaining up to date assets easier.

**Comment by Repraance** [comment]
So you mean these files could be visited from Github raw content/GitCDN, not pre-pulled to local?

**Comment by scj643** [comment]
This would make it so you would do `git submodule init` and then `git submodule update`

https://github.com/blog/2104-working-with-submodules

**Comment by Repraance** [comment]
OK, I got it. Now submodule is in `data/maps`. Thanks so much!
